### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Talljack** [Talljack/vscode-package-version#5]
- [x]  package version request optimization
	https spent time 21507ms < npm view package version 27998ms

- [x]  currentVersion with latestVersion diff bug

![img_v3_028b_893c1332-dd0b-4622-91c1-0e23f319fe3g](https://github.com/Talljack/vscode-package-version/assets/34439652/09f96288-7d2a-4aa7-975e-6037dcb5fc9a)
![img_v3_028b_113b7fca-aea1-4b16-b7c2-db774bd720eg](https://github.com/Talljack/vscode-package-version/assets/34439652/48a71de3-d611-42be-910f-41ba2a71a437)

- [x] set latest version to storage

- [ ] maybe support click update package version to the latest version

- [x]  hit color needs to change of none patch type

- [x]  watch package.json package version change and update hit version

- [x]  don't show version hit in scripts

![image](https://github.com/Talljack/vscode-package-version/assets/34439652/39bad4e8-fe0f-43a1-83d1-5d77cd6f73e5)

- [ ] add configuration, auto show or by command to show
